version: "3.4"
services:
  etl:
    build:
      context: ./jobs/etl
      dockerfile: Dockerfile
      args:
        WORKFLOW: "${WORKFLOW}"
    deploy:
      resources:
        limits:
          memory: 30000M #975000M
    env_file:
      - ./jobs/etl/.env
    volumes:
      - /mnt/graphdata:/mnt/graphdata
  graph_learning:
    build:
      context: ./jobs/graph_learning
      dockerfile: Dockerfile
      args:
        WORKFLOW: "${WORKFLOW}"
    deploy:
      resources:
        limits:
          memory: 28000M
    env_file:
      - ./jobs/graph_learning/.env
    volumes:
      - /mnt/graphdata/:/mnt/graphdata
