version: "3.4"
services:
  etl:
    container_name: etl_container
    build:
      context: ./jobs/etl
      dockerfile: Dockerfile
      args:
        # WORKFLOW: sql_to_graph
        WORKFLOW: graph_to_projection
        TASK: all
    deploy:
      resources:
        limits:
          memory: 8000M
    env_file:
      - ./jobs/etl/.env
    volumes:
      - /mnt/graphdata:/mnt/graphdata
  graph_learning:
    container_name: graph_learning_container
    build:
      context: ./jobs/graph_learning
      dockerfile: Dockerfile
      args:
        # WORKFLOW: make_features
        # WORKFLOW: make_datasets
        # WORKFLOW: link_prediction_gds
        WORKFLOW: link_prediction_pyg
        TASK: all
    env_file:
      - ./jobs/graph_learning/.env
    volumes:
      - /mnt/graphdata/:/mnt/graphdata
